# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_auto_20161114_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='passwd',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
